@CatalogApi_HostAddress = https://localhost:7147

POST {{CatalogApi_HostAddress}}/api/Products

###

POST {{CatalogApi_HostAddress}}/api/Products
Content-Type: application/json
Accept:application/json

{
  "name":"Kefli",
  "price":8.4,
  "description":"kefliDesc"
}
###

GET {{CatalogApi_HostAddress}}/api/products

###

GET {{CatalogApi_HostAddress}}/api/products?q=bis


###

GET {{CatalogApi_HostAddress}}/api/products/4

###

